### ISSUE TITLE
Testing on other OSes

### ISSUE THREAD

**Issue by espetro** [lostkeys/Typora-Lostkeys-Theme#2]
Hello there!

I am currently using the `Lostkeys` theme on Typora in **Ubuntu**. However, I can also use it on my 2nd **Windows** partition. As I have seen, this OSes has not been tested yet, so: how can I run a complete test for the theme?

**Comment by lostkeys** [comment]
Thanks! There is no test suite so you can simply try to use all features of the editor (mainly the sidebar, code blocks etc) and see if there is no apparent wonkiness in the UI.
