### ISSUE TITLE
So many bug in dark theme

### ISSUE THREAD

**Issue by OiCkilL** [lostkeys/Typora-Lostkeys-Theme#5]
<img width="948" alt="2018-04-19 3 06 47" src="https://user-images.githubusercontent.com/613988/38976248-5259b100-43e3-11e8-9327-8938d9d36997.png">
Code background and sidebar background are not good.

**Comment by cmeeren** [comment]
There are similar issues with the Preferences dialog.

I would love for this to be fixed. It's the only thing preventing me from using this beautiful theme. :)

**Comment by lostkeys** [comment]
Sorry for taking ages to get back here. Github didn't send me any email notifications and I honestly didn't expect any activity here. Anyway, these issues should have been addressed. Please reopen this issue if you find some place left unstyled.
